doc_ref: http://localhost:3338/swagger/doc.json
log_level: debug
database:
  sqlite:
    path: data
    filename: database.sqlite
mint:
  host: 0.0.0.0
  port: 3338
  private_key: veryverysecretkey
  derivation_path: 0/0/0/0
  tls:
    enabled: false
    key_path: /home/tls.key
    cert_path: /home/tls.crt
lightning:
  enabled: false
  lnbits:
    lightning_fee_percent: 1.0
    lightning_reserve_fee_min: 4000
    admin_key: 1234567897894531351ab513154
    url: https://legend.lnbits.com